
package tacotitos.ui;

public class Menu extends javax.swing.JFrame {

    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLtitle = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnNuevoPedido = new javax.swing.JButton();
        btnIngredientes = new javax.swing.JButton();
        btnTipoIngrediente = new javax.swing.JButton();
        btnResumen = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLimg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLtitle.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLtitle.setText("Tacotito's food truck");

        btnNuevoPedido.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnNuevoPedido.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\Desktop\\tacotitos\\icon achicado\\pedido-removebg-preview-removebg-preview.png")); // NOI18N
        btnNuevoPedido.setText("Nuevo Pedido");
        btnNuevoPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoPedidoActionPerformed(evt);
            }
        });

        btnIngredientes.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnIngredientes.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\Desktop\\tacotitos\\icon achicado\\dieta-removebg-preview-removebg-preview.png")); // NOI18N
        btnIngredientes.setText("Ingredientes");
        btnIngredientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngredientesActionPerformed(evt);
            }
        });

        btnTipoIngrediente.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnTipoIngrediente.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\Desktop\\tacotitos\\icon achicado\\ingredientes-removebg-preview-removebg-preview.png")); // NOI18N
        btnTipoIngrediente.setText("Tipo de Ingredientes");
        btnTipoIngrediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTipoIngredienteActionPerformed(evt);
            }
        });

        btnResumen.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnResumen.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\Desktop\\tacotitos\\icon achicado\\estadisticas-removebg-preview-removebg-preview.png")); // NOI18N
        btnResumen.setText("  Resumen");

        btnSalir.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnSalir.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\Desktop\\tacotitos\\icon achicado\\salida-de-emergencia-removebg-preview.png")); // NOI18N
        btnSalir.setText("  Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSalir)
                    .addComponent(btnTipoIngrediente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnIngredientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNuevoPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnResumen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(btnNuevoPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnIngredientes, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTipoIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnResumen, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jLimg.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\Desktop\\tacotitos\\tmex.png")); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLtitle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLimg, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLtitle, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLimg, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 965, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoPedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevoPedidoActionPerformed

    private void btnIngredientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngredientesActionPerformed
        //hago que cuando aprete el boton de ingredientes me muestre la ventana de ingredientes
        Ingredientes pantalla = new Ingredientes();//crea la instancia de nueva pantalla
        pantalla.setVisible(true); //va a hacer visible la pantalla
        pantalla.setLocationRelativeTo(null);//hace que la ventana aparezca en el centro de la pantalla
        this.dispose();
        
    }//GEN-LAST:event_btnIngredientesActionPerformed

    private void btnTipoIngredienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTipoIngredienteActionPerformed
       //hago que cuando aprete el boton de tipo de ingredientes me muestre la ventana de tipo de ingredientes
        Tipo_ingredientes pantalla = new Tipo_ingredientes();//crea la instancia de nueva pantalla
        pantalla.setVisible(true); //va a hacer visible la pantalla
        pantalla.setLocationRelativeTo(null);//hace que la ventana aparezca en el centro de la pantalla
        this.dispose();
    }//GEN-LAST:event_btnTipoIngredienteActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
      
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngredientes;
    private javax.swing.JButton btnNuevoPedido;
    private javax.swing.JButton btnResumen;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnTipoIngrediente;
    private javax.swing.JLabel jLimg;
    private javax.swing.JLabel jLtitle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
