
package tacotitos.ui;

import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import tacotitos.logica.Controladora;
import tacotitos.logica.Ingrediente;
import tacotitos.logica.Tipo_Ingrediente;



public class modificarIngrediente extends javax.swing.JFrame {
    //atributos de la clase
    Controladora control = null;
    //lo declaro como variable global
    Ingrediente ingre ;
    List <Tipo_Ingrediente> listTipo ;
   
   
    //constructor
    public modificarIngrediente(int id) {
        //instancio la controladora de logica
        control = new Controladora();
        //inicia todos los componentes de la vista
        initComponents();
        //llamo al metodo cargar form para que me llene los campos con la informacion de la base de datos 
        cargarForm(id);   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelForm = new javax.swing.JPanel();
        lbPrecio = new javax.swing.JLabel();
        lbTipo = new javax.swing.JLabel();
        lbNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        cmbIngre = new javax.swing.JComboBox<>();
        panelBtnForm = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Modificar ingrediente");

        lbPrecio.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbPrecio.setText("Precio: ");

        lbTipo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbTipo.setText("Tipo de ingrediente:");

        lbNombre.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbNombre.setText("Nombre:");

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        cmbIngre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbIngreActionPerformed(evt);
            }
        });

        btnGuardar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnGuardar.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\Desktop\\tacotitos\\icon achicado\\salvar-removebg-preview-removebg-preview.png")); // NOI18N
        btnGuardar.setText(" Guardar cambios");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnLimpiar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnLimpiar.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\Desktop\\tacotitos\\icon achicado\\limpiar-removebg-preview-removebg-preview.png")); // NOI18N
        btnLimpiar.setText("  Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBtnFormLayout = new javax.swing.GroupLayout(panelBtnForm);
        panelBtnForm.setLayout(panelBtnFormLayout);
        panelBtnFormLayout.setHorizontalGroup(
            panelBtnFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBtnFormLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnGuardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(btnLimpiar)
                .addGap(24, 24, 24))
        );
        panelBtnFormLayout.setVerticalGroup(
            panelBtnFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBtnFormLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelBtnFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80))
        );

        javax.swing.GroupLayout panelFormLayout = new javax.swing.GroupLayout(panelForm);
        panelForm.setLayout(panelFormLayout);
        panelFormLayout.setHorizontalGroup(
            panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFormLayout.createSequentialGroup()
                        .addComponent(lbTipo)
                        .addGap(18, 18, 18)
                        .addComponent(cmbIngre, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(panelFormLayout.createSequentialGroup()
                            .addComponent(lbPrecio)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelFormLayout.createSequentialGroup()
                            .addComponent(lbNombre)
                            .addGap(34, 34, 34)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))))
            .addGroup(panelFormLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelBtnForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelFormLayout.setVerticalGroup(
            panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPrecio)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTipo)
                    .addComponent(cmbIngre, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(panelBtnForm, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                .addContainerGap(88, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(116, 116, 116))
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void cmbIngreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbIngreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbIngreActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        
        int id = capturarIdCmb();
        //le paso por parametro los datos que capturo del Jform
        control.modificarIngrediente(ingre,txtNombre.getText(),Float.valueOf(txtPrecio.getText()),id);
       
        // creo un cartel cuando me crea el objeto
         mostrarMensaje("Se actualizaron los datos con exito","info","Actualizacion exitosa");
         limpiar();
         
         //cierro ventana ingrediente
         Ingredientes ventana = new Ingredientes();
         ventana.setVisible(true);
         ventana.setLocationRelativeTo(null);
         //le digo que se cierre la ventana cuando se edite
         this.dispose();
       
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
      
        cargarCmbTipo(cmbIngre);
    }//GEN-LAST:event_formWindowOpened

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JComboBox<String> cmbIngre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbNombre;
    private javax.swing.JLabel lbPrecio;
    private javax.swing.JLabel lbTipo;
    private javax.swing.JPanel panelBtnForm;
    private javax.swing.JPanel panelForm;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
 
    
    
    private void cargarForm(int id) {
        //traigo la informacion del objeto con el id que viene por parametro
        this.ingre = control.traerIngrediente(id);
        
        //seteo el valor de los campos con los valores del objeto     
        txtNombre.setText(ingre.getNombre());
        txtPrecio.setText(String.valueOf(ingre.getPrecio()));
        //con el combo box tengo que utilizar los indices ya que no es igual que un text, asigno el indice 0 que tendria que ser el vacio
    
        }
        
      
    //metodo para vaciar los campos del formulario
    private void limpiar() {
        txtNombre.setText(" ");
        txtPrecio.setText(" ");
        //con el combo box tengo que utilizar los indices ya que no es igual que un text, asigno el indice 0 que tendria que ser el vacio
        cmbIngre.setSelectedIndex(0);
    }
 
    
    //metodo para mostrar mensajes
   private void mostrarMensaje(String msj, String tipo, String titulo){
        //creo un cartel 
        //JoptionPane que es un panel de opcion y le asignamos el msj que queramos
        JOptionPane optionPane = new JOptionPane(msj);
        //seleccionamos que tipo de msj queremos que aparezca
        //si es igual a info le asignamos un tipo de msj informacion
        if(tipo.equals("info")){
            optionPane.setMessageType(JOptionPane.INFORMATION_MESSAGE);
        }else if(tipo.equals("error")){
            optionPane.setMessageType(JOptionPane.ERROR_MESSAGE);
        }
        //instanciamos el dialogo osea la ventana que queremos que aparezca  y hacemos que este dentro del OpcionPane que creamos
        //y lo creamos 
        JDialog dialog = optionPane.createDialog(titulo);
        //posicionamos la ventana
        dialog.setAlwaysOnTop(true);
        //hacemos que este visible
        dialog.setVisible(true);
    }
   
   
    //metodo para cargar el combobox de tipo con los registros que tengo en la base de datos
    private void cargarCmbTipo(JComboBox cmb){
        
        listTipo = control.traerTipo_Ingredientes();
        
        
        DefaultComboBoxModel modeloCmb = new DefaultComboBoxModel();
       
        modeloCmb.addElement(" ");
        
        if(listTipo != null){
             //por cada tipo de ingrediente en la lista tipo cargamelas en cmb
             for(Tipo_Ingrediente tipo : listTipo){
                  
                 //agregamos en una fila el objeto tipo
                 modeloCmb.addElement(tipo.getDescripcion());
             }
            
         }
        //le asigno el modelo del cmb al cmb del form
        cmb.setModel(modeloCmb); 
    }

     public int capturarIdCmb(){
        
        //a una variable le asigno el indice seleccionado 
        int inx = cmbIngre.getSelectedIndex();
        //si la variable es mayor a 1 le resto uno porq la posicion 0 esta vacia
        if(inx>0){
            inx -= 1;
        }
       // retorno declaro el id del objeto seleccionado    
     return listTipo.get(inx).getId_tipo();
    }
}


