
package tacotitos.ui;

import java.util.List;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import tacotitos.logica.Controladora;
import tacotitos.logica.Tipo_Ingrediente;


public class Tipo_ingredientes extends javax.swing.JFrame {
    //instancio la controladora de la logica  
    Controladora control = new Controladora();
    
    
    public Tipo_ingredientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelGral = new javax.swing.JPanel();
        panelForm = new javax.swing.JPanel();
        lbCantmax = new javax.swing.JLabel();
        lbNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        spnCantMax = new javax.swing.JSpinner();
        btnAgregar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnLimpiar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        panelAbm = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTipo = new javax.swing.JTable();
        panelBtnAbm = new javax.swing.JPanel();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        lbTitulo = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lbCantmax.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbCantmax.setText("Cantidad Maxima:");

        lbNombre.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbNombre.setText("Nombre:");

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        btnAgregar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnAgregar.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\Desktop\\tacotitos\\icon achicado\\agregar-removebg-preview.png")); // NOI18N
        btnAgregar.setText(" Nuevo");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnLimpiar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnLimpiar.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\Desktop\\tacotitos\\icon achicado\\limpiar-removebg-preview-removebg-preview.png")); // NOI18N
        btnLimpiar.setText("  Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnGuardar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnGuardar.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\Desktop\\tacotitos\\icon achicado\\salvar-removebg-preview-removebg-preview.png")); // NOI18N
        btnGuardar.setText(" Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btnGuardar)
                .addGap(41, 41, 41)
                .addComponent(btnLimpiar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        panelAbm.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tblTipo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblTipo);

        btnModificar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnModificar.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\Desktop\\tacotitos\\icon achicado\\editar-documento-removebg-preview-removebg-preview.png")); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnEliminar.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\Desktop\\tacotitos\\icon achicado\\eliminar-removebg-preview-removebg-preview.png")); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBtnAbmLayout = new javax.swing.GroupLayout(panelBtnAbm);
        panelBtnAbm.setLayout(panelBtnAbmLayout);
        panelBtnAbmLayout.setHorizontalGroup(
            panelBtnAbmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBtnAbmLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btnModificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(btnEliminar)
                .addGap(46, 46, 46))
        );
        panelBtnAbmLayout.setVerticalGroup(
            panelBtnAbmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBtnAbmLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBtnAbmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelAbmLayout = new javax.swing.GroupLayout(panelAbm);
        panelAbm.setLayout(panelAbmLayout);
        panelAbmLayout.setHorizontalGroup(
            panelAbmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAbmLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAbmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelBtnAbm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelAbmLayout.setVerticalGroup(
            panelAbmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAbmLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(panelBtnAbm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout panelFormLayout = new javax.swing.GroupLayout(panelForm);
        panelForm.setLayout(panelFormLayout);
        panelFormLayout.setHorizontalGroup(
            panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormLayout.createSequentialGroup()
                .addGroup(panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFormLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelFormLayout.createSequentialGroup()
                        .addGroup(panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelFormLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelFormLayout.createSequentialGroup()
                                        .addComponent(lbCantmax)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(spnCantMax, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelFormLayout.createSequentialGroup()
                                        .addComponent(lbNombre)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFormLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(28, 28, 28)))
                .addComponent(panelAbm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(124, 124, 124))
        );
        panelFormLayout.setVerticalGroup(
            panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCantmax)
                    .addComponent(spnCantMax, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
            .addGroup(panelFormLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelAbm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lbTitulo.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lbTitulo.setText("Tipos de Ingredientes");

        btnSalir.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnSalir.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\Desktop\\tacotitos\\icon achicado\\salida-de-emergencia-removebg-preview.png")); // NOI18N
        btnSalir.setText("  Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelGralLayout = new javax.swing.GroupLayout(panelGral);
        panelGral.setLayout(panelGralLayout);
        panelGralLayout.setHorizontalGroup(
            panelGralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGralLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbTitulo)
                .addGap(147, 147, 147)
                .addComponent(btnSalir)
                .addGap(14, 14, 14))
            .addGroup(panelGralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelForm, javax.swing.GroupLayout.PREFERRED_SIZE, 1025, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelGralLayout.setVerticalGroup(
            panelGralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGralLayout.createSequentialGroup()
                .addGroup(panelGralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGralLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnSalir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGralLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbTitulo)
                        .addGap(18, 18, 18)))
                .addComponent(panelForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panelGral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        //seteo los text con una cadena vacia 
        limpiar();  
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarActionPerformed

    
    
    
    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
      
        //controlo si la tabla no esta vacia con el metodo getRowCount que me devuelve la cant de filas 
        if(tblTipo.getRowCount() > 0){
            //controlo si esta una fila seleccionada
            if(tblTipo.getSelectedRow() != -1){
                //capturo el id de la fila seleccionada
                //todos los datos cuando se cargan en una tabla son string 
                //le digo de la tabla tipo traeme el valor que esta en la columna 0 de la fila seleccionada, lo convierto en string y luego en entero
                int id_tipo = Integer.parseInt(String.valueOf(tblTipo.getValueAt(tblTipo.getSelectedRow(),0)));
                
                //llamo a la controladora de la logica 
                control.borrarTipo(id_tipo);
                
                //aviso si se borro correctamente 
                mostrarMensaje("Tipo de ingrediente eliminado correctamente", "info", "Eliminacion exitosa");
                //vuelvo a llamar al metodo cargar tabla para mostrarla actualizada despues de cada cambio
                cargarTabla();
        
               
            }
            //si no hay nada seleccionado aviso que no se pudo borrar 
            else{
                mostrarMensaje("No se selecciono ningun tipo de ingrediente","Error","Error al eliminar");
            }
            
        }
         //si no hay nada en la tabla aviso que no se pudo borrar 
        else{
            mostrarMensaje("No hay elementos para eliminar en la tabla","Error","Error al eliminar");
        }
        
       
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        
        //controlo si la tabla no esta vacia con el metodo getRowCount que me devuelve la cant de filas 
        if(tblTipo.getRowCount() > 0){
            //controlo si esta una fila seleccionada
            if(tblTipo.getSelectedRow() != -1){
                //capturo el id de la fila seleccionada para editar
                //todos los datos cuando se cargan en una tabla son string 
                //le digo de la tabla tipo traeme el valor que esta en la columna 0 de la fila seleccionada, lo convierto en string y luego en entero
                int id_tipo = Integer.parseInt(String.valueOf(tblTipo.getValueAt(tblTipo.getSelectedRow(),0)));
                
                //cuando hago click en editar se va abrir la ventana modificar 
                modificarTipo_ingrediente ventModificar = new modificarTipo_ingrediente(id_tipo);
                //la hago visible
                ventModificar.setVisible(true);
                //para que se abra en el centro 
                ventModificar.setLocationRelativeTo(null);
                //cerrar la ventana
                this.dispose();
              
            }
            //si no hay nada seleccionado aviso que no se pudo borrar 
            else{
                mostrarMensaje("No se selecciono ningun tipo de ingrediente","Error","Error al eliminar");
            }
            
        }
         //si no hay nada en la tabla aviso que no se pudo borrar 
        else{
            mostrarMensaje("No hay elementos para editar en la tabla","Error","Error al eliminar");
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
       
        //le paso por parametro los datos que capturo del Jform
        control.guardarTipo(txtNombre.getText(),(int)spnCantMax.getValue());
        
        // creo un cartel cuando me crea el objeto 
        //JoptionPane que es un panel de opcion y le asignamos el msj que queramos
        JOptionPane optionPane = new JOptionPane("se guardo correctamente");
        //seleccionamos que tipo de msj queremos que aparezca
        optionPane.setMessageType(JOptionPane.INFORMATION_MESSAGE);
        //instanciamos el dialogo osea la ventana que queremos que aparezca  y hacemos que este dentro del OpcionPane que creamos
        //y lo creamos 
        JDialog dialog = optionPane.createDialog("Guardado con exito");
        //posicionamos la ventana
        dialog.setAlwaysOnTop(true);
        //hacemos que este visible
        dialog.setVisible(true);
        
        limpiar();
         //vuelvo a llamar al metodo cargar tabla para mostrarla actualizada despues de cada cambio
        cargarTabla();
        
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        //esto va a ocurrir ni bien abro la ventana
        //llamo al metodo cargar tabla, que va a llamar a la controladora de la logia y esta va a llamar a la cont de la persistencia
        //para que traiga todo lo datos que estan cargados en la base de datos 
        cargarTabla();
    }//GEN-LAST:event_formWindowOpened

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
        Menu ventMenu = new Menu();
        ventMenu.setVisible(true);
        ventMenu.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnSalirActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbCantmax;
    private javax.swing.JLabel lbNombre;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JPanel panelAbm;
    private javax.swing.JPanel panelBtnAbm;
    private javax.swing.JPanel panelForm;
    private javax.swing.JPanel panelGral;
    private javax.swing.JSpinner spnCantMax;
    private javax.swing.JTable tblTipo;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables

    private void cargarTabla() {
        
        //definir el modelo que queremos que tenga la table, a traves de la clase defaul tablemodel
        //esta clase nos permite establecer un modelo a nuestra tabla 
        
        //hacemos que no se pueda editar el contenido de la tabla, todo el bloque pertenece a la instancia de tabla:
        DefaultTableModel modeloTabla = new DefaultTableModel(){
            //del defaultTableModel que cree que se llama tabla hace que todas las celdas sean 
            //filas o columnas no se puedan editar, que sean fijas
            @Override
            public boolean isCellEditable(int row,int colum){
                return false;
            }
        };//pongo punto y como porque todo lo anterior forma parte de la instancia de la tabla 
        
        
        //establecemos los titulos de las columnas 
        
        String titulos[] = {"Id", "Descripcion", "Cantidad maxima"};
        //setamos los titulos en la tabla
        modeloTabla.setColumnIdentifiers(titulos);
        
        //carga de los datos desde la base de dato, declaro una lista y le asigno lo que me trae el metodo de la controladora
         List <Tipo_Ingrediente> listTipo = control.traerTipo_Ingredientes();
        
         //recorrer y mostrar los elementos de la lista en la tabla
         // si mi lista no esta vacia entonces:
         if(listTipo != null){
             //por cada tipo de ingrediente en la lista tipo cargamelas en la tabla
             for(Tipo_Ingrediente tipo : listTipo){
                 
                 //vamos a crear un array de tipo objeto
                 Object[] objTipo = { tipo.getId_tipo(), tipo.getDescripcion(), tipo.getCantMax()};
                 
                 //agregamos en una fila el objeto tipo
                 modeloTabla.addRow(objTipo);
             }
             
         }
         
         //le asigno el modelo de la tabla a mi tabla
         tblTipo.setModel(modeloTabla);
         
    
    
    }
    
   
    //vaciar el contenido de los campos del form
    private void limpiar(){
        txtNombre.setText("");
        spnCantMax.setValue(0);
    }
    
    //ventana de mensaje
    
    private void mostrarMensaje(String msj,String tipo, String titulo){
        //creo un cartel 
        //JoptionPane que es un panel de opcion y le asignamos el msj que queramos
        JOptionPane optionPane = new JOptionPane(msj);
        //seleccionamos que tipo de msj queremos que aparezca
        //si es igual a info le asignamos un tipo de msj informacion
        if(tipo.equals("info")){
            optionPane.setMessageType(JOptionPane.INFORMATION_MESSAGE);
        }else if(tipo.equals("error")){
            optionPane.setMessageType(JOptionPane.ERROR_MESSAGE);
        }
        //instanciamos el dialogo osea la ventana que queremos que aparezca  y hacemos que este dentro del OpcionPane que creamos
        //y lo creamos 
        JDialog dialog = optionPane.createDialog(titulo);
        //posicionamos la ventana
        dialog.setAlwaysOnTop(true);
        //hacemos que este visible
        dialog.setVisible(true);
    }
}
